App/config/routes.rb
Rails.application.routes.draw do
  resources :pizzeria_points
  resources :storages
  resources :ingredients_prices
  resources :pizza_orders do
    put 'complete', on: :member
  end
  resources :pizza_sizes
  resources :adresses
  resources :pizza_types
  root 'home#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

App/app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :pizzeria_point

  validates :name, :available_cheese, :available_ham, :available_sauce, :available_pineapple, :pizzeria_point, presence: true
  validates :name, uniqueness: { scope: :pizzeria_point }, on: :create

  def self.search(search)
    if search
        where('name LIKE ?', "%#{search}%")
    else
        all
    end
  end
end

App/app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_storage, only: %i[ show edit update destroy ]

  def check_admin
    redirect_to root_path, notice: 'You are not an admin' if !current_user.admin
  end

  # GET /storages or /storages.json
  def index
    @storages = Storage.search(params[:search]).includes(:pizzeria_point.name).order(sort_column(Storage.column_names + ["pizzeria_points.name"]) + " " + sort_direction)
  end

  # GET /storages/1 or /storages/1.json
  def show
  end

  # GET /storages/new
  def new
    @storage = Storage.new
  end

  # GET /storages/1/edit
  def edit
  end

  # POST /storages or /storages.json
  def create
    @storage = Storage.new(storage_params)

    respond_to do |format|
      if @storage.save
        format.html { redirect_to storage_url(@storage), notice: "Storage was successfully created." }
        format.json { render :show, status: :created, location: @storage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1 or /storages/1.json
  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html { redirect_to storage_url(@storage), notice: "Storage was successfully updated." }
        format.json { render :show, status: :ok, location: @storage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1 or /storages/1.json
  def destroy
    @storage.destroy

    respond_to do |format|
      format.html { redirect_to storages_url, notice: "Storage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storage
      @storage = Storage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def storage_params
      params.require(:storage).permit(:name, :available_cheese, :available_ham, :available_sauce, :available_pineapple, :pizzeria_point_id)
    end
end

App/app/helpers/storages_helper.rb
module StoragesHelper
end

App/app/views/storages/_form.html.erb
<%= simple_form_for(@storage) do |f| %>
  <%= errors_for(@storage) %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :available_cheese %>
    <%= f.input :available_ham %>
    <%= f.input :available_sauce %>
    <%= f.input :available_pineapple %>
    <%= f.association :pizzeria_point %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

App/app/views/storages/_storage.html.erb
<div id="<%= dom_id storage %>">
  <p>
    <strong>Name:</strong>
    <%= storage.name %>
  </p>

  <p>
    <strong>Available cheese:</strong>
    <%= storage.available_cheese %>
  </p>

  <p>
    <strong>Available ham:</strong>
    <%= storage.available_ham %>
  </p>

  <p>
    <strong>Available sauce:</strong>
    <%= storage.available_sauce %>
  </p>

  <p>
    <strong>Available pineapple:</strong>
    <%= storage.available_pineapple %>
  </p>

  <p>
    <strong>Pizzeria point:</strong>
    <%= storage.pizzeria_point_id %>
  </p>

</div>

App/app/views/storages/edit.html.erb
<h1>Editing Storages</h1>


<%= render 'form', storage: @storage %>

<%= link_to 'Show', @storage %> |
<%= link_to 'Back', storages_path %>

App/app/views/storages/index.html.erb
<h1>Storages</h1>

<%= form_tag storages_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction]%>
  <%= hidden_field_tag :sort, params[:sort]%>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col"><%= sortable "name", "Name" %> </th>
      <th scope="col"><%= sortable "available_cheese", "Available cheese" %> </th>
      <th scope="col"><%= sortable "available_ham", "Available ham" %> </th>
      <th scope="col"><%= sortable "available_sauce", "Available sauce" %> </th>
      <th scope="col"><%= sortable "available_pineapple", "Available pineapple" %> </th>
      <th scope="col"><%= sortable "pizzeria_points.name", "Pizzeria point" %> </th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @storages.each do |storage| %>
      <tr>
        <td><%= storage.name %></td>
        <td><%= storage.available_cheese %></td>
        <td><%= storage.available_ham %></td>
        <td><%= storage.available_sauce %></td>
        <td><%= storage.available_pineapple %></td>
        <td><%= storage.pizzeria_point.name %></td>
        <td><%= link_to 'Show', storage %></td>
        <td><%= link_to 'Edit', edit_storage_path(storage) %></td>
        <td><%= link_to 'Destroy', storage, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Storage', new_storage_path %>

App/app/views/storages/new.html.erb
<h1>New Storages</h1>

<%= render 'form', storage: @storage %>

<%= link_to 'Back', storages_path %>

App/app/views/storages/show.html.erb
<h1>Storages</h1>

<dl>
  <dt>Name:</dt>
  <dd><%= @storage.name %></dd>
  <dt>Available cheese:</dt>
  <dd><%= @storage.available_cheese %></dd>
  <dt>Available ham:</dt>
  <dd><%= @storage.available_ham %></dd>
  <dt>Available sauce:</dt>
  <dd><%= @storage.available_sauce %></dd>
  <dt>Available pineapple:</dt>
  <dd><%= @storage.available_pineapple %></dd>
  <dt>Pizzeria point:</dt>
  <dd><%= link_to @storage.pizzeria_point.name, pizzeria_points_path(@storage.pizzeria_point) %></dd>
</dl>
<%= link_to 'Edit', edit_storage_path(@storage) %> |
<%= link_to 'Back', storages_path %>