App/config/routes.rb
Rails.application.routes.draw do
  resources :pizzeria_points
  resources :storages
  resources :ingredients_prices
  resources :pizza_orders do
    put 'complete', on: :member
  end
  resources :pizza_sizes
  resources :adresses
  resources :pizza_types
  root 'home#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

App/app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

App/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "PizzApp", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Sizes", pizza_sizes_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Types", pizza_types_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Pizzeria points", pizzeria_points_path, class:"nav-link"%>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Orders", pizza_orders_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Adresses", adresses_path, class:"nav-link"%>
          </li>

          <% if current_user.admin%>
            <li class="nav-item">
              <%= link_to "Storages", storages_path, class:"nav-link"%>
            </li>

            <li class="nav-item">
              <%= link_to "Prices", ingredients_prices_path, class:"nav-link"%>
            </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.email, edit_user_registration_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
    <% if notice %>
        <%= render 'layouts/alerts' %>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>