App/config/routes.rb
Rails.application.routes.draw do
  resources :pizzeria_points
  resources :storages
  resources :ingredients_prices
  resources :pizza_orders do
    put 'complete', on: :member
  end
  resources :pizza_sizes
  resources :adresses
  resources :pizza_types
  root 'home#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

App/app/models/pizzeria_point.rb
class PizzeriaPoint < ApplicationRecord
  belongs_to :ingredients_price
  has_many :storages

  validates :name, :ingredients_price, presence: true
  validates :name, uniqueness: true

  def self.search(search)
    if search
        where('name LIKE ?', "%#{search}%")
    else
        all
    end
  end
end

App/app/controllers/pizzeria_points_controller.rb
class PizzeriaPointsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :check_admin, except: %i[ index show ]
  before_action :set_pizzeria_point, only: %i[ show edit update destroy ]

  def check_admin
    redirect_to root_path, notice: 'You are not an admin' if !current_user.admin
  end

  # GET /pizzeria_points or /pizzeria_points.json
  def index
    @pizzeria_points = PizzeriaPoint.search(params[:search]).includes(:ingredients_price.name).order(sort_column(PizzeriaPoint.column_names + ["ingredients_prices.name"]) + " " + sort_direction)
  end

  # GET /pizzeria_points/1 or /pizzeria_points/1.json
  def show
  end

  # GET /pizzeria_points/new
  def new
    @pizzeria_point = PizzeriaPoint.new
  end

  # GET /pizzeria_points/1/edit
  def edit
  end

  # POST /pizzeria_points or /pizzeria_points.json
  def create
    @pizzeria_point = PizzeriaPoint.new(pizzeria_point_params)

    respond_to do |format|
      if @pizzeria_point.save
        format.html { redirect_to pizzeria_point_url(@pizzeria_point), notice: "Pizzeria point was successfully created." }
        format.json { render :show, status: :created, location: @pizzeria_point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pizzeria_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzeria_points/1 or /pizzeria_points/1.json
  def update
    respond_to do |format|
      if @pizzeria_point.update(pizzeria_point_params)
        format.html { redirect_to pizzeria_point_url(@pizzeria_point), notice: "Pizzeria point was successfully updated." }
        format.json { render :show, status: :ok, location: @pizzeria_point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pizzeria_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzeria_points/1 or /pizzeria_points/1.json
  def destroy
    @pizzeria_point.destroy

    respond_to do |format|
      format.html { redirect_to pizzeria_points_url, notice: "Pizzeria point was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizzeria_point
      @pizzeria_point = PizzeriaPoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pizzeria_point_params
      params.require(:pizzeria_point).permit(:name, :ingredients_price_id)
    end
end

App/app/helpers/pizzeria_points_helper.rb
module PizzeriaPointsHelper
end

App/app/views/pizzeria_points/_form.html.erb
<%= simple_form_for(@pizzeria_point) do |f| %>
  <%= errors_for(@pizzeria_point) %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :ingredients_price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

App/app/views/pizzeria_points/_pizzeria_point.html.erb
<div id="<%= dom_id pizzeria_point %>">
  <p>
    <strong>Name:</strong>
    <%= pizzeria_point.name %>
  </p>

  <p>
    <strong>Ingredients price:</strong>
    <%= pizzeria_point.ingredients_price_id %>
  </p>

</div>

App/app/views/pizzeria_points/edit.html.erb
<h1>Editing Pizzeria Points</h1>


<%= render 'form', pizzeria_point: @pizzeria_point %>

<%= link_to 'Show', @pizzeria_point %> |
<%= link_to 'Back', pizzeria_points_path %>

App/app/views/pizzeria_points/index.html.erb
<h1>Pizzeria Points</h1>

<%= form_tag pizzeria_points_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction]%>
  <%= hidden_field_tag :sort, params[:sort]%>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col"><%= sortable "name", "Name" %> </th>
      <th scope="col">Ingredients price</th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizzeria_points.each do |pizzeria_point| %>
      <tr>
        <td><%= pizzeria_point.name %></td>
        <td><%= pizzeria_point.ingredients_price.name %></td>
        <td><%= link_to 'Show', pizzeria_point %></td>
        <% if current_user && current_user.admin %>
          <td><%= link_to 'Edit', edit_pizzeria_point_path(pizzeria_point) %></td>
          <td><%= link_to 'Destroy', pizzeria_point, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin %>
  <%= link_to 'New Pizzeria Point', new_pizzeria_point_path %>
<% end %>

App/app/views/pizzeria_points/new.html.erb
<h1>New Pizzeria Points</h1>

<%= render 'form', pizzeria_point: @pizzeria_point %>

<%= link_to 'Back', pizzeria_points_path %>

App/app/views/pizzeria_points/show.html.erb
<h1>Pizzeria Points</h1>

<dl>
  <dt>Name:</dt>
  <dd><%= @pizzeria_point.name %></dd>
  <dt>Ingredients price:</dt>
  <dd><%= link_to @pizzeria_point.ingredients_price.name, ingredients_price_path(@pizzeria_point.ingredients_price) %></dd>
</dl>
<%= link_to 'Edit', edit_pizzeria_point_path(@pizzeria_point) %> |
<%= link_to 'Back', pizzeria_points_path %>