App/config/routes.rb
Rails.application.routes.draw do
  resources :pizzeria_points
  resources :storages
  resources :ingredients_prices
  resources :pizza_orders do
    put 'complete', on: :member
  end
  resources :pizza_sizes
  resources :adresses
  resources :pizza_types
  root 'home#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

App/app/models/pizza_order.rb
class PizzaOrder < ApplicationRecord
  belongs_to :pizza_type
  belongs_to :pizza_size
  belongs_to :adress
  belongs_to :pizzeria_point
  has_many :storages, through: :pizzeria_point

  validates :ingredients_multiplayer, :pizza_type, :pizza_size, :adress, :pizzeria_point, presence: true

  before_save do |order|
    price = 0
    type = order.pizza_type
    prices = order.pizzeria_point.ingredients_price
    multiplayer = order.ingredients_multiplayer

    price += order.pizza_size.basic_price
    price += multiplayer * (type.required_cheese * prices.cheese_price)
    price += multiplayer * (type.required_ham * prices.ham_price)
    price += multiplayer * (type.required_sauce * prices.sauce_price)
    price += multiplayer * (type.required_pineapple * prices.pineapple_price)

    order.total_price = price
  end

  def self.search(search)
    if search && !search.empty?
      where(id: search)
    else
      all
    end
  end
end

App/app/controllers/pizza_orders_controller.rb
class PizzaOrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pizza_order, only: %i[ show edit update destroy complete ]
  before_action :isCompleted, only: %i[ edit update destroy ]
  before_action :canComplete, only: %i[ complete ]

  def pizzaOrderWithNames
    return PizzaOrder.search(params[:search]).includes(:pizza_type.name, :pizza_size.name, :adress.name, :pizzeria_point.name)
  end

  # GET /pizza_orders or /pizza_orders.json
  def index
    if current_user.admin
      @pizza_orders = pizzaOrderWithNames.order(sort_column(COLUMN_NAMES) + " " + sort_direction)
    else
      @pizza_orders = current_user.pizza_orders.search(params[:search]).includes(:pizza_type.name, :pizza_size.name, :adress.name, :pizzeria_point.name).order(sort_column(COLUMN_NAMES) + " " + sort_direction)
    end
  end

  # GET /pizza_orders/1 or /pizza_orders/1.json
  def show
  end

  # GET /pizza_orders/new
  def new
    @pizza_order = current_user.pizza_orders.build
  end

  # GET /pizza_orders/1/edit
  def edit
  end

  def canComplete
    redirect_to pizza_orders_path, notice: "Can't complete order" if @pizza_order.date_of_order || !current_user.admin
  end

  def isCompleted
    redirect_to pizza_orders_path, notice: 'Order is completed' if @pizza_order.date_of_order && !current_user.admin
  end

  # POST /pizza_orders or /pizza_orders.json
  def create
    @pizza_order = current_user.pizza_orders.build(pizza_order_params)

    respond_to do |format|
      if @pizza_order.save
        format.html { redirect_to pizza_order_url(@pizza_order), notice: "Pizza order was successfully created." }
        format.json { render :show, status: :created, location: @pizza_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pizza_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizza_orders/1 or /pizza_orders/1.json
  def update
    respond_to do |format|
      if @pizza_order.update(pizza_order_params)
        format.html { redirect_to pizza_order_url(@pizza_order), notice: "Pizza order was successfully updated." }
        format.json { render :show, status: :ok, location: @pizza_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pizza_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def checkStorages
    needed_cheese = @pizza_order.ingredients_multiplayer * @pizza_order.pizza_type.required_cheese
    needed_sauce = @pizza_order.ingredients_multiplayer * @pizza_order.pizza_type.required_sauce
    needed_ham = @pizza_order.ingredients_multiplayer * @pizza_order.pizza_type.required_ham
    needed_pineapple = @pizza_order.ingredients_multiplayer * @pizza_order.pizza_type.required_pineapple

    cheese = 0
    sauce = 0
    ham = 0
    pineapple = 0

    can_be_done = false

    @pizza_order.storages.each do |s|
      cheese += s.available_cheese
      sauce += s.available_sauce
      ham += s.available_ham
      pineapple += s.available_pineapple

      if cheese >= needed_cheese && sauce >= needed_sauce && ham >= needed_ham && pineapple >= needed_pineapple
        can_be_done = true
        break
      end
    end

    if can_be_done
      @pizza_order.storages.each do |s|
        s.available_cheese -= [s.available_cheese, needed_cheese].min
        needed_cheese -= [s.available_cheese, needed_cheese].min
        s.available_sauce -= [s.available_sauce, needed_sauce].min
        needed_sauce -= [s.available_sauce, needed_sauce].min
        s.available_ham -= [s.available_ham, needed_ham].min
        needed_ham -= [s.available_ham, needed_ham].min
        s.available_pineapple -= [s.available_pineapple, needed_pineapple].min
        needed_pineapple -= [s.available_pineapple, needed_pineapple].min
        s.save(validate: false)

        if needed_cheese == 0 && needed_sauce == 0 && needed_ham == 0 && needed_pineapple == 0
          break
        end
      end
    end

    return can_be_done
  end

  def complete
    if checkStorages
      respond_to do |format|
        if @pizza_order.update_attribute(:date_of_order, Time.now)
          format.html { redirect_to pizza_orders_path, notice: "Pizza order completed." }
          format.json { render :show, status: :ok, location: @pizza_order }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @pizza_order.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to pizza_orders_path, notice: 'Not enough ingredients in storages'
    end
  end

  # DELETE /pizza_orders/1 or /pizza_orders/1.json
  def destroy
    @pizza_order.destroy

    respond_to do |format|
      format.html { redirect_to pizza_orders_url, notice: "Pizza order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza_order
      @pizza_order = PizzaOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pizza_order_params
      params.require(:pizza_order).permit(:ingredients_multiplayer, :pizza_type_id, :pizza_size_id, :adress_id, :pizzeria_point_id)
    end

    COLUMN_NAMES = PizzaOrder.column_names + ["pizza_types.name", "pizza_sizes.name", "adresses.name", "pizzeria_points.name"]
end

App/app/helpers/pizza_orders_helper.rb
module PizzaOrdersHelper
end

App/app/views/pizza_orders/_form.html.erb
<%= simple_form_for(@pizza_order) do |f| %>
  <%= errors_for(@pizza_order) %>

  <div class="form-inputs">
    <%= f.input :ingredients_multiplayer %>
    <%= f.association :pizza_type %>
    <%= f.association :pizza_size %>
    <%= f.association :adress, collection: current_user.adresses %>
    <%= f.association :pizzeria_point %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

App/app/views/pizza_orders/_pizza_order.html.erb
<div id="<%= dom_id pizza_order %>">
  <p>
    <strong>Ingredients multiplayer:</strong>
    <%= pizza_order.ingredients_multiplayer %>
  </p>

  <p>
    <strong>Pizza type:</strong>
    <%= pizza_order.pizza_type_id %>
  </p>

  <p>
    <strong>Pizza size:</strong>
    <%= pizza_order.pizza_size_id %>
  </p>

  <p>
    <strong>Adress:</strong>
    <%= pizza_order.adress_id %>
  </p>

  <p>
    <strong>Pizzeria point:</strong>
    <%= pizza_order.pizzeria_point_id %>
  </p>

</div>

App/app/views/pizza_orders/edit.html.erb
<h1>Editing Pizza Orders</h1>


<%= render 'form', pizza_order: @pizza_order %>

<%= link_to 'Show', @pizza_order %> |
<%= link_to 'Back', pizza_orders_path %>

App/app/views/pizza_orders/index.html.erb
<h1>Pizza Orders</h1>

<%= form_tag pizza_orders_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction]%>
  <%= hidden_field_tag :sort, params[:sort]%>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col"><%= sortable "id", "Order id" %> </th>
      <th scope="col"><%= sortable "total_price", "Total price" %> </th>
      <th scope="col"><%= sortable "pizza_types.name", "Pizza type" %> </th>
      <th scope="col"><%= sortable "pizza_sizes.name", "Pizza size" %> </th>
      <th scope="col"><%= sortable "adresses.name", "Adress" %> </th>
      <th scope="col"><%= sortable "pizzeria_points.name", "Pizzeria point" %> </th>
      <th scope="col"><%= sortable "date_of_order", "Completed" %> </th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizza_orders.each do |pizza_order| %>
      <tr>
        <td><%= pizza_order.id %></td>
        <td><%= pizza_order.total_price %></td>
        <td><%= pizza_order.pizza_type.name %></td>
        <td><%= pizza_order.pizza_size.name %></td>
        <td><%= pizza_order.adress.name %></td>
        <td><%= pizza_order.pizzeria_point.name %></td>
        <td><%= pizza_order.date_of_order %></td>
        <td><%= link_to 'Show', pizza_order %></td>

        <% if pizza_order.user_id == current_user.id || current_user.admin %>
          <td><%= link_to 'Edit', edit_pizza_order_path(pizza_order) %></td>
          <td><%= link_to 'Destroy', pizza_order, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
        <% end %>

        <% if !pizza_order.date_of_order && current_user.admin %>
          <td><%= button_to 'Complete', complete_pizza_order_path(pizza_order), method: :put %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Pizza Order', new_pizza_order_path %>

App/app/views/pizza_orders/new.html.erb
<h1>New Pizza Orders</h1>

<%= render 'form', pizza_order: @pizza_order %>

<%= link_to 'Back', pizza_orders_path %>

App/app/views/pizza_orders/show.html.erb
<h1>Pizza Orders</h1>

<dl>
  <dt>Ingredients multiplayer:</dt>
  <dd><%= @pizza_order.ingredients_multiplayer %></dd>
  <dt>Total price:</dt>
  <dd><%= @pizza_order.total_price %></dd>
  <dt>Pizza type:</dt>
  <dd><%= link_to @pizza_order.pizza_type.name, pizza_type_path(@pizza_order.pizza_type) %></dd>
  <dt>Pizza size:</dt>
  <dd><%= link_to @pizza_order.pizza_size.name, pizza_size_path(@pizza_order.pizza_size) %></dd>
  <dt>Adress:</dt>
  <dd><%= link_to @pizza_order.adress.name, adress_path(@pizza_order.adress) %></dd>
  <dt>Pizzeria point:</dt>
  <dd><%= link_to @pizza_order.pizzeria_point.name, pizzeria_point_path(@pizza_order.pizzeria_point) %></dd>
</dl>
<%= link_to 'Edit', edit_pizza_order_path(@pizza_order) %> |
<%= link_to 'Back', pizza_orders_path %>